name: Build and Deploy .NET Core

on:
  push:
    branches: [ main ]

env:
 AZURE_WEBAPP_NAME: gha-demo
 AZURE_WEBAPP_PACKAGE_PATH: './GitHubActionsDemo.API'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet 5.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
      - name: Dotnet build and Publish
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish'
      - uses: azure/webapps-deploy@v2
       with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish'
