name: Build and Test .NET 5

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    stages:
      - uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test